# example_config.toml

# Section for specifying the language model to use
[llm_model]
model_id = "example_model_id" # Replace with the actual model ID

# Section for specifying language channels
[language_channels]
korean = 123456789012345678 # Replace with the actual channel ID
chinese = 123456789012345678 # Replace with the actual channel ID
hindi = 123456789012345678 # Replace with the actual channel ID
japanese = 123456789012345678 # Replace with the actual channel ID
french = 123456789012345678 # Replace with the actual channel ID
vietnamese = 123456789012345678 # Replace with the actual channel ID
spanish = 123456789012345678 # Replace with the actual channel ID

# Section for specifying the target channel
[target_channel]
target_channel_id = 123456789012345678 # Replace with the actual channel ID

# Section for specifying monitored channels
[monitored_channels]
channels = [
    123456789012345678, # Replace with the actual channel ID
    123456789012345678, # Replace with the actual channel ID
    123456789012345678, # Replace with the actual channel ID
    123456789012345678, # Replace with the actual channel ID
    123456789012345678, # Replace with the actual channel ID
    123456789012345678, # Replace with the actual channel ID
    123456789012345678, # Replace with the actual channel ID
    123456789012345678, # Replace with the actual channel ID
]

# Section for specifying the Discord prompt
[discord_prompt]
prompt = """
You are a helpful AI assistant. Your task is to identify the language of the user message. Then translate it to {language}. Your response should be the translation of the original user message. Provide the translation in a clear, concise, and natural-sounding manner. Maintain the original meaning and tone of the message.
Please translate the message. Only include the translated contents and nothing else
"""